name: passkeys_windows
description: Windows implementation of the passkeys plugin. Manages the creation of passkeys on Windows devices using Windows Hello and WebAuthn API.
homepage: https://docs.corbado.com/overview/welcome
repository: https://github.com/corbado/flutter-passkeys/tree/main/packages/passkeys/passkeys_windows
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: passkeys
    platforms:
      windows:
        pluginClass: PasskeysWindowsPlugin
        dartPluginClass: PasskeysWindows

dependencies:
  flutter:
    sdk: flutter
  passkeys_platform_interface:
    path: ../passkeys_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^11.0.1
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0
