name: corbado_auth
description: Flutter package for Corbado Auth. Enables authentication on Android and iOS using passkeys.
homepage: https://docs.corbado.com/overview/welcome
repository: https://github.com/corbado/flutter-passkeys/tree/main/packages/corbado_auth
version: 3.4.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  built_collection: ^5.1.1
  corbado_frontend_api_client: ^2.1.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_keychain: ^2.4.0
  http: ^1.1.2
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  meta: ^1.15.0
  passkeys: ^2.7.1
  rxdart: ^0.27.7
  ua_client_hints: ^1.1.3
  universal_html: ^2.2.4

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0