name: corbado_auth
description: Corbado auth flutter package
homepage: https://docs.corbado.com/overview/welcome
repository: https://github.com/corbado/flutter-passkeys/tree/main/packages/corbado_auth
version: 0.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  corbado_frontend_api_client: ^0.1.1
  flutter:
    sdk: flutter
  flutter_keychain: ^2.2.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  passkeys: ^0.1.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
