name: corbado_auth
description: Corbado auth flutter package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_keychain: ^2.2.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  passkeys:
    path: ../passkeys/passkeys
  openapi_generator_annotations: ^4.10.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  openapi_generator: ^4.10.0
