name: corbado_frontend_api_client
description: Flutter client for the most recent version of the Corbado frontend API.
homepage: https://docs.corbado.com/overview/welcome
repository: https://github.com/corbado/flutter-passkeys/tree/main/packages/corbado_api_client
version: 1.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  openapi_generator_annotations: ^5.0.2
  http: ^1.2.1
  intl: ^0.19.0
  meta: ^1.12.0
  collection: ^1.15.0

dev_dependencies:
  openapi_generator: ^5.0.2
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
