name: passkeys_example
description: Demonstrates how to use the passkeys plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  corbado_auth: ^2.0.7
  flutter:
    sdk: flutter
  passkeys: ^2.0.9
  go_router: ^10.1.2
  flutter_hooks: ^0.20.3
  riverpod: ^2.3.10
  flutter_riverpod: ^2.3.10
  hooks_riverpod: 2.4.0
  corbado_frontend_api_client: ^1.1.1
  flutter_localization: ^0.2.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

