name: passkeys_example
description: Demonstrates how to use the passkeys plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  passkeys:
    path: ../
  go_router: ^10.1.2
  flutter_hooks: ^0.20.3
  riverpod: ^2.3.10
  flutter_riverpod: ^2.3.10
  hooks_riverpod: 2.4.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

