name: passkeys
description: A flutter package to enable passkey authentication.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: passkeys_android
      ios:
        default_package: passkeys_ios

dependencies:
  convert: ^3.1.1
  corbado_api:
    path: lib/relying_party_server/corbado/generated
  flutter:
    sdk: flutter
  http: '>=0.13.0 <0.14.0'
  json_annotation: ^4.8.1
  openapi_generator_annotations: ^4.10.0
  passkeys_android:
    path: ../passkeys_android
  passkeys_ios:
    path: ../passkeys_ios
  passkeys_platform_interface:
    path: ../passkeys_platform_interface

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  openapi_generator: ^4.10.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0
