name: passkeys
description: Flutter plugin enabling simple passkey authentication. Can be either used with a ready-to-use relying party server (Corbado) or with your custom relying party.
homepage: https://docs.corbado.com/overview/welcome
repository: https://github.com/corbado/flutter-passkeys/tree/main/packages/passkeys/passkeys
version: 1.3.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: passkeys_android
      ios:
        default_package: passkeys_ios

dependencies:
  convert: ^3.1.1
  corbado_frontend_api_client: ^1.1.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1
  openapi_generator_annotations: ^4.10.0
  passkeys_android: ^1.2.1
  passkeys_ios: ^1.2.0
  passkeys_platform_interface: ^1.2.0
  ua_client_hints: ^1.1.3

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  openapi_generator: ^4.10.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0