name: passkeys
description: Flutter plugin enabling simple passkey authentication. Can be either used with a ready-to-use relying party server (Corbado) or with your custom relying party.
homepage: https://docs.corbado.com/overview/welcome
repository: https://github.com/corbado/flutter-passkeys/tree/main/packages/passkeys/passkeys
version: 2.17.3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: passkeys_android
      ios:
        default_package: passkeys_darwin
      macos:
        default_package: passkeys_darwin
      web:
        default_package: passkeys_web
      windows:
        default_package: passkeys_windows

dependencies:
  convert: ^3.1.1
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  passkeys_android: ^2.11.0
  passkeys_darwin: ^0.3.0
  passkeys_doctor: ^1.2.0
  passkeys_platform_interface: ^2.6.0
  passkeys_web: ^2.8.0
  passkeys_windows: ^0.1.1
  ua_client_hints: ^1.1.3

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0
